apiVersion: v1
kind: Service
metadata:
  name: cowsay-service
  namespace: cowsay
  labels:
    app: cowsay
spec:
  type: LoadBalancer
  selector:
    app: cowsay
  ports:
  - name: webserver
    protocol: TCP
    port: 8080
    targetPort: 80